2022-12-10 00:11:09,358 INFO werkzeug MainThread : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2022-12-10 00:11:09,358 INFO werkzeug MainThread : [33mPress CTRL+C to quit[0m
2022-12-10 00:11:15,791 ERROR app Thread-1 (process_request_thread) : Exception on /api/v1/delete_person [DELETE]
Traceback (most recent call last):
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\sqlalchemy\orm\attributes.py", line 327, in __getattr__
    return getattr(self.comparator, key)
AttributeError: 'Comparator' object has no attribute 'id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\app.py", line 82, in delete_person
    res = session.query(Person.phones).filter(Person.phones.id == data["id"]) \
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\sqlalchemy\orm\attributes.py", line 329, in __getattr__
    util.raise_(
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\sqlalchemy\util\compat.py", line 210, in raise_
    raise exception
AttributeError: Neither 'InstrumentedAttribute' object nor 'Comparator' object associated with Person.phones has an attribute 'id'
2022-12-10 00:11:15,796 INFO werkzeug Thread-1 (process_request_thread) : 127.0.0.1 - - [10/Dec/2022 00:11:15] "[35m[1mDELETE /api/v1/delete_person HTTP/1.1[0m" 500 -
2022-12-10 00:12:56,197 INFO werkzeug MainThread : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2022-12-10 00:12:56,197 INFO werkzeug MainThread : [33mPress CTRL+C to quit[0m
2022-12-10 00:13:01,093 INFO werkzeug Thread-1 (process_request_thread) : 127.0.0.1 - - [10/Dec/2022 00:13:01] "DELETE /api/v1/delete_person HTTP/1.1" 200 -
2022-12-10 00:23:52,186 INFO werkzeug MainThread : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2022-12-10 00:23:52,187 INFO werkzeug MainThread : [33mPress CTRL+C to quit[0m
2022-12-10 00:24:13,882 INFO werkzeug Thread-1 (process_request_thread) : 127.0.0.1 - - [10/Dec/2022 00:24:13] "DELETE /api/v1/delete_person HTTP/1.1" 200 -
2022-12-10 00:25:07,442 INFO werkzeug MainThread : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2022-12-10 00:25:07,442 INFO werkzeug MainThread : [33mPress CTRL+C to quit[0m
2022-12-10 00:25:14,822 INFO werkzeug Thread-1 (process_request_thread) : 127.0.0.1 - - [10/Dec/2022 00:25:14] "DELETE /api/v1/delete_person HTTP/1.1" 200 -
2022-12-10 00:26:05,011 INFO werkzeug MainThread : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2022-12-10 00:26:05,012 INFO werkzeug MainThread : [33mPress CTRL+C to quit[0m
2022-12-10 00:26:12,505 INFO werkzeug Thread-1 (process_request_thread) : 127.0.0.1 - - [10/Dec/2022 00:26:12] "DELETE /api/v1/delete_person HTTP/1.1" 200 -
2022-12-10 00:33:57,070 INFO werkzeug MainThread : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2022-12-10 00:33:57,071 INFO werkzeug MainThread : [33mPress CTRL+C to quit[0m
2022-12-10 00:34:34,220 ERROR app Thread-1 (process_request_thread) : Exception on /api/v1/num_visits [GET]
Traceback (most recent call last):
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\redis\connection.py", line 598, in connect
    sock = self.retry.call_with_retry(
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\redis\retry.py", line 46, in call_with_retry
    return do()
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\redis\connection.py", line 599, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\redis\connection.py", line 664, in _connect
    raise err
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\redis\connection.py", line 652, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\app.py", line 23, in num_visits
    count = get_hit_counts()
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\utils.py", line 12, in get_hit_counts
    raise exc
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\utils.py", line 9, in get_hit_counts
    return cache.incr('hits')
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\redis\commands\core.py", line 1852, in incrby
    return self.execute_command("INCRBY", name, amount)
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\redis\client.py", line 1255, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\redis\connection.py", line 1389, in get_connection
    connection.connect()
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\redis\connection.py", line 604, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
2022-12-10 00:34:34,251 INFO werkzeug Thread-1 (process_request_thread) : 127.0.0.1 - - [10/Dec/2022 00:34:34] "[35m[1mGET /api/v1/num_visits HTTP/1.1[0m" 500 -
2022-12-10 00:34:35,653 INFO app Thread-3 (process_request_thread) : All users were selected from database
2022-12-10 00:34:35,654 INFO werkzeug Thread-3 (process_request_thread) : 127.0.0.1 - - [10/Dec/2022 00:34:35] "GET /api/v1/get_all_people_data HTTP/1.1" 200 -
2022-12-10 00:34:35,676 INFO app Thread-4 (process_request_thread) : All users were selected from database
2022-12-10 00:34:35,677 INFO werkzeug Thread-4 (process_request_thread) : 127.0.0.1 - - [10/Dec/2022 00:34:35] "GET /api/v1/get_all_people_data HTTP/1.1" 200 -
2022-12-10 00:34:49,054 ERROR app Thread-2 (process_request_thread) : Exception on /api/v1/num_visits [GET]
Traceback (most recent call last):
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\redis\connection.py", line 598, in connect
    sock = self.retry.call_with_retry(
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\redis\retry.py", line 46, in call_with_retry
    return do()
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\redis\connection.py", line 599, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\redis\connection.py", line 664, in _connect
    raise err
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\redis\connection.py", line 652, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\app.py", line 23, in num_visits
    count = get_hit_counts()
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\utils.py", line 12, in get_hit_counts
    raise exc
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\utils.py", line 9, in get_hit_counts
    return cache.incr('hits')
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\redis\commands\core.py", line 1852, in incrby
    return self.execute_command("INCRBY", name, amount)
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\redis\client.py", line 1255, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\redis\connection.py", line 1389, in get_connection
    connection.connect()
  File "C:\Users\ACER\Documents\2022_fall\БД\labs\main_project\server\venv\lib\site-packages\redis\connection.py", line 604, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
2022-12-10 00:34:49,054 INFO werkzeug Thread-2 (process_request_thread) : 127.0.0.1 - - [10/Dec/2022 00:34:49] "[35m[1mGET /api/v1/num_visits HTTP/1.1[0m" 500 -
2022-12-10 12:12:49,821 INFO werkzeug MainThread : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2022-12-10 12:12:49,821 INFO werkzeug MainThread : [33mPress CTRL+C to quit[0m
2022-12-10 12:14:02,458 INFO werkzeug Thread-1 (process_request_thread) : 127.0.0.1 - - [10/Dec/2022 12:14:02] "POST /api/v1/add_person HTTP/1.1" 200 -
2022-12-10 12:14:38,050 INFO app Thread-2 (process_request_thread) : All users were selected from database
2022-12-10 12:14:38,051 INFO werkzeug Thread-2 (process_request_thread) : 127.0.0.1 - - [10/Dec/2022 12:14:38] "GET /api/v1/get_all_people_data HTTP/1.1" 200 -
2022-12-10 12:14:45,191 INFO werkzeug Thread-3 (process_request_thread) : 127.0.0.1 - - [10/Dec/2022 12:14:45] "DELETE /api/v1/delete_person HTTP/1.1" 200 -
2022-12-10 12:15:55,158 INFO werkzeug Thread-4 (process_request_thread) : 127.0.0.1 - - [10/Dec/2022 12:15:55] "PUT /api/v1/upd_phone HTTP/1.1" 200 -
2022-12-10 12:17:41,162 INFO werkzeug Thread-5 (process_request_thread) : 127.0.0.1 - - [10/Dec/2022 12:17:41] "PUT /api/v1/upd_firstname HTTP/1.1" 200 -
2022-12-10 12:17:56,605 INFO werkzeug Thread-6 (process_request_thread) : 127.0.0.1 - - [10/Dec/2022 12:17:56] "PUT /api/v1/upd_lastname HTTP/1.1" 200 -
2022-12-10 12:18:29,073 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [10/Dec/2022 12:18:29] "PUT /api/v1/upd_position HTTP/1.1" 200 -
2022-12-10 12:24:42,190 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [10/Dec/2022 12:24:42] "POST /api/v1/add_position HTTP/1.1" 200 -
2022-12-10 12:28:54,631 INFO werkzeug MainThread : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2022-12-10 12:28:54,631 INFO werkzeug MainThread : [33mPress CTRL+C to quit[0m
2022-12-10 12:28:58,378 INFO werkzeug Thread-1 (process_request_thread) : 127.0.0.1 - - [10/Dec/2022 12:28:58] "DELETE /api/v1/delete_position HTTP/1.1" 200 -
2022-12-10 12:32:20,966 INFO werkzeug MainThread : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2022-12-10 12:32:20,966 INFO werkzeug MainThread : [33mPress CTRL+C to quit[0m
2022-12-10 12:32:23,064 INFO app Thread-1 (process_request_thread) : All users were selected from database
2022-12-10 12:32:23,065 INFO werkzeug Thread-1 (process_request_thread) : 127.0.0.1 - - [10/Dec/2022 12:32:23] "GET /api/v1/get_all_positions HTTP/1.1" 200 -
2022-12-10 13:07:01,931 INFO werkzeug MainThread : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2022-12-10 13:07:01,931 INFO werkzeug MainThread : [33mPress CTRL+C to quit[0m
2022-12-10 13:08:28,537 INFO werkzeug Thread-1 (process_request_thread) : 127.0.0.1 - - [10/Dec/2022 13:08:28] "PUT /api/v1/upd_position HTTP/1.1" 200 -
